version: '3'

services:  
  jenkins:
    build:
        context: .
    container_name: jenkins
    #image: guysoft/jenkins-sudo:lts
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home:
